const data = [
  {
    name: "Baldur's Gate 3",
    genre: "RPG",
    price: "$60",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "highVio",
    Players: "both",
    img: "images/baldurs_gate3.png",
    url: "baldurs_gate3.html",
  },
  {
    name: "Celeste",
    genre: "Platformer",
    price: "$20",
    platform: "all",
    world: "linear",
    hours: "15-30",
    violence: "noVio",
    Players: "single",
    img: "images/celeste.png",
    url: "celeste.html",
    id: 2
  },
  {
    name: "Chicory: A Colorful Tale",
    genre: "Action",
    price: "$20",
    platform: "all",
    world: "openWorld",
    hours: "15-30",
    violence: "noVio",
    Players: "both",
    img: "images/chicory.png",
    url: "chicory.html",
  },
  {
    name: "Cyberpunk 2077",
    genre: "RPG",
    price: "$60",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "highVio",
    Players: "singleplayer",
    img: "images/cyberpunk2077.png",
    url: "cyberpunk2077.html",
  },
  {
    name: "Deep Rock Galactic",
    genre: "Shooter",
    price: "$30",
    platform: "all",
    world: "openWorld",
    length: "31+",
    violence: "moderateVio",
    Players: "multiplayer",
    img: "images/deep_rock.png",
    url: "deep_rock.html",
  },

  {
    name: "DOOM Eternal",
    genre: "Shooter",
    price: "$15",
    platform: "all",
    world: "linear",
    hours: "15-30",
    violence: "highVio",
    Players: "singleplayer",
    img: "images/doom_eternal.png",
    url: "doom_eternal.html",
  },
  {
    name: "Fallout: New Vegas",
    genre: "Rpg",
    price: "$10",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "highVio",
    Players: "singleplayer",
    img: "images/fallout_nv.png",
    url: "fallout_nv.html",
  },

  {
    name: "Firewatch",
    genre: "Narrative",
    price: "$4",
    platform: "all",
    world: "linear",
    hours: "0-5",
    violence: "lowVio",
    Players: "singleplayer",
    img: "images/firewatch.png",
    url: "firewatch.html",
  },
  {
    name: "Genshin Impact",
    genre: "RPG",
    price: "Free",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "moderateVio",
    Players: "both",
    img: "images/genshin_impact.png",
    url: "genshin_impact.html",

 },
 {
  name: "Hades",
  genre: "Rpg",
  price: "$25",
  platform: "all",
  world: "mixed",
  hours: "15-30",
  violence: "highVio",
  Players: "singleplayer",
  img: "images/hades.png",
  url: "hades.html",
  },
  {
    name: "Hollow Knight",
    genre: "Action",
    price: "$8",
    platform: "all",
    world: "openWorld",
    hours: "15-30",
    violence: "moderateVio",
    Players: "singleplayer",
    img: "images/hollow_knight.png",
    url: "hollow_knight.html",
  },
  {
    name: "It Takes Two",
    genre: "Patformer",
    price: "$39.99",
    platform: "all",
    world: "linear",
    hours: "15-30",
    violence: "lowVio",
    Players: "multiplayer",
    img: "images/it_takes_two.png",
    url: "it_takes_two.html",
  },
  {
    name: "Journey",
    genre: "Action",
    price: "$15",
    platform: "pc",
    world: "linear",
    hours: "0-5",
    violence: "noVio",
    Players: "both",
    img: "images/journey.png",
    url: "journey.html",

  },
  {
    name: "League of Legends",
    genre: "Action",
    price: "Free",
    platform: "pc",
    world: "linear",
    hours: "31+",
    violence: "moderateVio",
    Players: "multiplayer",
    img: "images/league_of_legends.png",
    url: "league_of_legends.html",

  },
  {
    name: "Minecraft",
    genre: "Survival",
    price: "$29.99",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "moderateVio",
    Players: "both",
    img: "images/minecraft.png",
    url: "minecraft.html",
  },
  {
    name: "Outer Wilds",
    genre: "Action",
    price: "$24.99",
    platform: "all",
    world: "open",
    hours: "15-30",
    violence: "lowVio",
    Players: "singleplayer",
    img: "images/outer_wilds.png",
    url: "outer_wilds.html",
  },
  {
    name: "Overwatch 2",
    genre: "Shooter",
    price: "Free",
    platform: "all",
    world: "linear",
    hours: "31+",
    violence: "moderateVio",
    Players: "multiplayer",
    img: "images/overwatch2.png",
    url: "overwatch2.html",

  },
  {
    name: "Papers, Please",
    genre: "Puzzle",
    price: "$9.99",
    platform: "pc",
    world: "linear",
    hours: "5-15",
    violence: "moderateVio",
    Players: "singleplayer",
    img: "images/papers_please.png",
    url: "papers_please.html",
  },
  {
    name: "Red Dead Redemption 2",
    genre: "Action",
    price: "$60",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "highVio",
    Players: "both",
    img: "images/rdr2.png",
    url: "rdr2.html",
  },
  {
    name: "Return of the Obra Dinn",
    genre: "Puzzle",
    price: "$20",
    platform: "all",
    world: "openWorld",
    hours: "15-30",
    violence: "lowVio",
    Players: "singleplayer",
    img: "images/obra_dinn.png",
    url: "obra_dinn.html",
  },
  {
    name: "Slay the Spire",
    genre: "Puzzle",
    price: "$7",
    platform: "all",
    world: "linear",
    hours: "5-15",
    violence: "lowVio",
    Players: "singleplayer",
    img: "images/slay_the_spire.png",
    url: "slay_the_spire.html",
  },
  {
    name: "Stardew Valley",
    genre: "Simulator",
    price: "$15",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "noVio",
    Players: "both",
    img: "images/stardew_valley.png",
    url: "stardew_valley.html",
  },
  {
    name: "Subnautica",
    genre: "Survival",
    price: "$15",
    platform: "all",
    world: "openWorld",
    hours: "15-30",
    violence: "moderateVio",
    Players: "singleplayer",
    img: "images/subnautica.png",
    url: "subnautica.html",
  },
  {
    name: "Terraria",
    genre: "Survival",
    price: "$10",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "moderateVio",
    Players: "both",
    img: "images/terraria.png",
    url: "terraria.org",
  },
  {
    name: "Tetris Effect",
    genre: "Puzzle",
    price: "$40",
    platform: "all",
    world: "linear",
    hours: "5-15",
    violence: "noVio",
    Players: "both",
    img: "images/tetris_effect.png",
    url: "monstars.com/tetris-effect",
  },
  {
    name: "The Legend of Zelda: Breath of the Wild",
    genre: "Action",
    price: "$40",
    platform: "console",
    world: "openWorld",
    hours: "31+",
    violence: "moderateVio",
    Players: "singleplayer",
    img: "images/zelda_botw.png",
    url: "zelda.nintendo.com",
  },
  {
    name: "The Sims 4",
    genre: "Simulator",
    price: "$40",
    platform: "all",
    world: "openWorld",
    hours: "31+",
    violence: "noVio",
    Players: "singleplayer",
    img: "images/sims4.png",
    url: "ea.com/thesims",
  },
  {
    name: "The Witness",
    genre: "Puzzle",
    price: "$40",
    platform: "all",
    world: "openWorld",
    hours: "15-30",
    violence: "noVio",
    Players: "singleplayer",
    img: "images/the_witness.png",
    url: "the-witness.net",
  },
  {
    name: "Tunic",
    genre: "Action",
    price: "$30",
    platform: "all",
    world: "mixed",
    hours: "5-15",
    violence: "moderateVio",
    Players: "singleplayer",
    img: "images/tunic.png",
    url: "tunicgame.com",
  },
  {
    name: "Wattam",
    genre: "Puzzle",
    price: "$20",
    platform: "pc",
    world: "openWorld",
    hours: "5-15",
    violence: "noVio",
    Players: "both",
    img: "images/wattam.png",
    url: "wattamgame.com",
  }
]


window.addEventListener("DOMContentLoaded", () =>{
  displayGameData(data);
});

const productContainer = document.querySelector('.products_wrapper');


//display all games
function displayGameData(gamez) {
  let displayData = gamez.map(function(cat_items){
    return `<div class="products">
            <div class="pr_img">
              <img src="${cat_items.img}" alt="${cat_items.name}" width="215" height="250"/>
            </div>
            <div class="content">
              <h3 class="title">${cat_items.name}</h3>
              <p class="genre">${cat_items.genre}</p>
              <p class="price">${cat_items.price}</p>
             
            </div>
          </div>`;

  });
displayData = displayData.join("");
productContainer.innerHTML = displayData;
}


